#!/bin/bash

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIR=${DIR}/..
GU_CONFIG_LOCATION=~/.gu/pressreader/

setup_git_hook() {
  echo "Setting up pre-push hook"
  cp "${ROOT_DIR}/scripts/pre-push" "${ROOT_DIR}/.git/hooks/pre-push"
  chmod +x "${ROOT_DIR}/.git/hooks/pre-push"
}

setup_node_env() {
  echo "Attempting to switch node versions for you..."
  if command -v fnm &> /dev/null
  then
      fnm use
  else
    if command -v nvm &> /dev/null
    then
      echo "You are using 'nvm', 'fnm' is preferred (it's quicker)!"
      nvm use
    else
      echo "Please install fnm: 'brew install fnm'"
      exit 1
    fi
  fi
}

check_node_version() {
  runningNodeVersion=$(node -v)
  requiredNodeVersion=$(cat "$ROOT_DIR/.nvmrc")

  # remove leading v
  runningNodeVersionNumber=${runningNodeVersion//[v]/}

  if [ "$runningNodeVersionNumber" != "$requiredNodeVersion" ]; then
    echo -e "Using wrong version of Node. Required ${requiredNodeVersion}. Running ${runningNodeVersion}."
    setup_node_env
  fi
}

create_gu_config() {
  echo "Creating config in $GU_CONFIG_LOCATION"
  mkdir -p $GU_CONFIG_LOCATION

  CAPI_API_KEY=$(AWS_REGION=eu-west-1 AWS_PROFILE=printProd \
    aws secretsmanager get-secret-value \
    --secret-id /DEV/print-production/pressreader/capiToken \
    --query "SecretString" \
    --output text)

  echo $CAPI_API_KEY > $GU_CONFIG_LOCATION/capiKey
}

install_node_deps() {
  echo "Installing node dependencies"
  npm i
}

setup_git_hook
check_node_version
install_node_deps
create_gu_config

echo "You're all set up!"
